### ISSUE TITLE
Update 1.20 Todo

### ISSUE THREAD

**Issue by funnyboy-roks** [FarLandsMC/FarLands#44]
This is incomplete and should be expanded.

## FarLands

- [x] Update NMS (ew)
- [x] Don't remove `/editsign`
    - This is added natively by Mojang now, but we still want styling to
      not count for length
- [x] Make sure that the new sign editing functionality applies styling
    - Add staff logging
- [x] Make Pocket world reset automatically every 2 weeks
    - Use RP's safe block algo to set a spawm point
    - Ingame announcements 1 hour before, 10 min before, and 30 seconds before, like for restart
    - Lock the `/pocket` command when it's resetting
    - Kick everyone out before resetting
    - If possible, do this on another thread to help minimise lag
    - Maybe this should just be done when the server restarts?
    - Check day == Monday && weekOfYear % 2 == 0 for every other week on monday
- [x] Sus sand/gravel silk touch
    - Not able to be dusted after silk touch

## RegionProtection

- [x] Prevent signs in regions without build trust from being modified
- [x] Fix the issue with claims below y=0

## ChestShops

- [x] Prevent chest signs from being modified
- ~~[ ] Add option to use item display entity~~
    - Moved to ChestShops repo: FarLandsMC/ChestShops#26
